# Generated by Django 4.1 on 2022-09-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trend')),
            ],
            options={
                'verbose_name': 'Тренер',
            },
        ),
    ]
