# Generated by Django 4.1 on 2022-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
