# Generated by Django 4.1 on 2022-09-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trainer_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='workouts',
            field=models.IntegerField(default=0),
        ),
    ]
