# Generated by Django 4.1 on 2022-09-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='programs',
            field=models.IntegerField(default=0),
        ),
    ]
