# Generated by Django 4.1 on 2022-09-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trainer_picture_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('read_time', models.TimeField()),
                ('author', models.TextField()),
                ('direction', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Блог>',
            },
        ),
    ]
