# Generated by Django 4.1 on 2022-09-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='picture_src',
            field=models.CharField(default='', max_length=100),
        ),
    ]
