# Generated by Django 4.1 on 2022-09-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogpost_picture_src'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Блог'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.CharField(default='', max_length=5),
        ),
    ]
