# Generated by Django 4.1 on 2022-09-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_blogpost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
