# Generated by Django 4.1 on 2022-09-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_blogpost_pub_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_month',
            field=models.CharField(auto_created=True, choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default=models.DateField(auto_now_add=True), max_length=200),
        ),
    ]
