# Generated by Django 4.1 on 2022-09-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_blogpost_pub_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='pub_month',
        ),
    ]
