# Generated by Django 4.1 on 2022-09-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_blogpost_pub_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Направление',
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='direction',
            field=models.CharField(default='', max_length=20),
        ),
    ]
