# Generated by Django 4.1 on 2022-09-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_direction_alter_blogpost_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='direction',
        ),
    ]
