# Generated by Django 4.1 on 2022-09-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_blogpost_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.direction'),
        ),
    ]
