# Generated by Django 4.1 on 2022-09-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='trainer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.trainer'),
        ),
    ]
