# Generated by Django 4.1 on 2022-09-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_workout_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='direction',
            field=models.ManyToManyField(default='', through='core.Workout', to='core.direction'),
        ),
    ]
