# Generated by Django 4.1 on 2022-09-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_trainer_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='direction',
            field=models.ManyToManyField(through='core.Workout', to='core.direction'),
        ),
    ]
