# Generated by Django 4.1 on 2022-09-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='trainer',
        ),
    ]
