# Generated by Django 4.1 on 2022-09-20 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_remove_subscription_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='subscribers',
            field=models.ManyToManyField(default=0, through='core.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
