# Generated by Django 4.1 on 2022-09-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_workoutprogram_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, default='2018-11-20T15:58:44.767594-06:00'),
        ),
    ]
