# Generated by Django 4.1 on 2022-09-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_workoutprogram_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutprogram',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, default='2001-01-01T00:00:00.000000+03:00'),
        ),
    ]
