# Generated by Django 4.1 on 2022-09-23 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_alter_workoutprogram_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='direction',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trend'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='direction',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='directions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction'),
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('instagram', models.CharField(max_length=20)),
                ('mass', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sex', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
