# Generated by Django 4.1 on 2022-09-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_blogpost_direction_alter_trainer_trend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='picture_src',
            field=models.ImageField(upload_to=''),
        ),
    ]
