# Generated by Django 4.1 on 2022-09-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_trainer_picture_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='picture_src',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='picture_src',
            field=models.ImageField(upload_to=''),
        ),
    ]
