# Generated by Django 4.1 on 2022-09-24 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0038_alter_blogpost_picture_src_alter_feedback_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateField(auto_created=True)),
                ('num', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('promo', models.CharField(max_length=20)),
                ('sum', models.IntegerField()),
                ('date_expired', models.DateField(null=True)),
                ('type_of_sub', models.IntegerField(choices=[('1', 'Месяц'), ('3', '3 Месяца')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
