# Generated by Django 4.1 on 2022-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='type_of_sub',
        ),
        migrations.AlterField(
            model_name='payment',
            name='promo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
