# Generated by Django 4.1 on 2022-09-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_payment_type_of_sub_alter_payment_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='cur_pic_back',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='progress',
            name='cur_pic_front',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='progress',
            name='cur_pic_side',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='progress',
            name='prev_pic_back',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='progress',
            name='prev_pic_front',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='progress',
            name='prev_pic_side',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
