# Generated by Django 4.1 on 2022-09-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_progress_cur_pic_back_progress_cur_pic_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
