# Generated by Django 4.1 on 2022-09-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_progress_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='prev_pic_back',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='progress',
            name='prev_pic_front',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='progress',
            name='prev_pic_side',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
