# Generated by Django 4.1 on 2022-10-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_progress_prev_pic_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='program',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
